# Generated by Django 3.2.6 on 2022-11-08 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-updated_at', '-created_at']},
        ),
    ]
